version: '3.1'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  voting:
    build: .
    command: python3 ./src/manage.py
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb